import "./mytasks.css";

const MyTasks = () => {
  return <div>USE POST TO FIGURE OUT HOW TO DO IT. USERNAME ATTACHED TO (PUT) TASK BY ADMIN, USERNAME IS KEY. USE PUT METHOD TO ASSIGN THE USERNAME TO THE TASK. DOWNSIDE: ONLY ONE USER CAN BE ASSIGNED A TASK AT A TIME.</div>;
};

export default MyTasks;
